variables:
  COMMON_DNF_PACKAGES: autoconf automake libtool pam-devel make bison flex gettext-devel kbd kbd-legacy kbd-misc

distcheck:
  stage: test
  tags:
    - libvirt
  variables:
    CC: gcc
  before_script:
    - sudo dnf -y install gcc $COMMON_DNF_PACKAGES
  script:
    - ./autogen.sh
    - ./configure --datadir="$PWD/data" --enable-optional-progs --enable-libkeymap
    - make V=1
    - make distcheck

.check-base:
  stage: test
  tags:
    - libvirt
  variables:
    CHECK_KEYWORDS: unittest e2e
    SANDBOX: priviliged
  before_script:
    - sudo dnf -y install $COMMON_DNF_PACKAGES $EXTRA_DNF_PACKAGES
  script:
    - ./autogen.sh
    - ./configure --datadir="$PWD/data" --enable-optional-progs $EXTRA_CONFIGURE_OPTIONS
    - make V=1
    - sudo -E make check
  needs: ["distcheck"]
  artifacts:
    when: on_failure
    paths:
      - config.log
      - tests/testsuite.log

check-gcc-glibc:
  extends: .check-base
  variables:
    CC: gcc
    EXTRA_DNF_PACKAGES: gcc
    EXTRA_CONFIGURE_OPTIONS: --enable-libkeymap

check-clang-glibc:
  extends: .check-base
  variables:
    CC: clang
    EXTRA_DNF_PACKAGES: clang
    EXTRA_CONFIGURE_OPTIONS: --enable-libkeymap

check-gcc-musl:
  extends: .check-base
  variables:
    CC: musl-gcc -static -idirafter /usr/include/ -idirafter /usr/x86_64-linux-musl/include/
    EXTRA_DNF_PACKAGES: musl-gcc
    EXTRA_CONFIGURE_OPTIONS: --disable-libkeymap --disable-vlock
    CHECK_KEYWORDS: unittest
